# Constants
HRSA_CCT_TOOL: str = "HRSA_CCT_TOOL"

# Constants
BREAK_ROOM_NAME = "BreakRoom"
PATIENT_ROOM_NAME = "PatientRoom"
FEEDBACK_ROOM_NAME = "FeedbackRoom"
FEEDBACK_TYPE_BREAK_ROOM_NAME = "BreakRoomFeedback"
FEEDBACK_TYPE_PATIENT_ROOM_NAME = "PatientRoomFeedback"
DIALOGUE_INK_FILE_NAME = "dialogue.ink"
FEEDBACK_INK_FILE_NAME = "feedback.ink"
DIALOGUE_INK_JSON_FILE_NAME = "dialogue.json"
FEEDBACK_INK_JSON_FILE_NAME = "feedback.json"
AUDIO_FOLDER_NAME = "Audio"
SCENARIO_INFORMATION_JSON_FILE_NAME = "scenario_information.json"
CHARACTER_VOICE_CONFIG_JSON_FILE_NAME = "character_voice_config.json"
MAX_DIALOGUE_TEXT_CHARACTER_COUNT = 275  # 300 / 250
