# GUI Element Tags
PIU_PATIENT_FIRST_NAME_INPUT_TEXT: str = "PIU_PATIENT_FIRST_NAME_INPUT_TEXT"
PIU_PATIENT_LAST_NAME_INPUT_TEXT: str = "PIU_PATIENT_LAST_NAME_INPUT_TEXT"
PIU_PATIENT_MIDDLE_NAME_INPUT_TEXT: str = "PIU_PATIENT_MIDDLE_NAME_INPUT_TEXT"
PIU_PATIENT_SUFFIX_INPUT_TEXT: str = "PIU_PATIENT_SUFFIX_INPUT_TEXT"
PIU_PATIENT_PREVIOUS_NAME_INPUT_TEXT: str = "PIU_PATIENT_PREVIOUS_NAME_INPUT_TEXT"
PIU_PATIENT_DATE_OF_BIRTH_INPUT_TEXT: str = "PIU_PATIENT_DATE_OF_BIRTH_INPUT_TEXT"
PIU_PATIENT_DATE_OF_DEATH_INPUT_TEXT: str = "PIU_PATIENT_DATE_OF_DEATH_INPUT_TEXT"
PIU_PATIENT_AGE_INPUT_TEXT: str = "PIU_PATIENT_AGE_INPUT_TEXT"
PIU_PATIENT_RACE_INPUT_TEXT: str = "PIU_PATIENT_RACE_INPUT_TEXT"
PIU_PATIENT_ETHNICITY_INPUT_TEXT: str = "PIU_PATIENT_ETHNICITY_INPUT_TEXT"
PIU_PATIENT_TRIBAL_AFFILIATION_INPUT_TEXT: str = "PIU_PATIENT_TRIBAL_AFFILIATION_INPUT_TEXT"
PIU_PATIENT_SEX_ASSIGNED_AT_BIRTH_INPUT_TEXT: str = "PIU_PATIENT_SEX_ASSIGNED_AT_BIRTH_INPUT_TEXT"
PIU_PATIENT_SEXUAL_ORIENTATION_INPUT_TEXT: str = "PIU_PATIENT_SEXUAL_ORIENTATION_INPUT_TEXT"
PIU_PATIENT_GENDER_IDENTITY_INPUT_TEXT: str = "PIU_PATIENT_GENDER_IDENTITY_INPUT_TEXT"
PIU_PATIENT_PREFERRED_LANGUAGE_INPUT_TEXT: str = "PIU_PATIENT_PREFERRED_LANGUAGE_INPUT_TEXT"
PIU_PATIENT_CURRENT_ADDRESS_INPUT_TEXT: str = "PIU_PATIENT_CURRENT_ADDRESS_INPUT_TEXT"
PIU_PATIENT_PREVIOUS_ADDRESS_INPUT_TEXT: str = "PIU_PATIENT_PREVIOUS_ADDRESS_INPUT_TEXT"
PIU_PATIENT_PHONE_NUMBER_INPUT_TEXT: str = "PIU_PATIENT_PHONE_NUMBER_INPUT_TEXT"
PIU_PATIENT_PHONE_NUMBER_TYPE_INPUT_TEXT: str = "PIU_PATIENT_PHONE_NUMBER_TYPE_INPUT_TEXT"
PIU_PATIENT_EMAIL_ADDRESS_INPUT_TEXT: str = "PIU_PATIENT_EMAIL_ADDRESS_INPUT_TEXT"
PIU_PATIENT_RELATED_PERSONS_NAME_INPUT_TEXT: str = "PIU_PATIENT_RELATED_PERSONS_NAME_INPUT_TEXT"
PIU_PATIENT_RELATED_PERSONS_RELATIONSHIP_INPUT_TEXT: str = "PIU_PATIENT_RELATED_PERSONS_RELATIONSHIP_INPUT_TEXT"
PIU_PATIENT_OCCUPATION_INPUT_TEXT: str = "PIU_PATIENT_OCCUPATION_INPUT_TEXT"
PIU_PATIENT_OCCUPATION_HISTORY_INPUT_TEXT: str = "PIU_PATIENT_OCCUPATION_HISTORY_INPUT_TEXT"
PIU_PATIENT_CHIEF_COMPLAINT_INPUT_TEXT: str = "PIU_PATIENT_CHIEF_COMPLAINT_INPUT_TEXT"
PIU_PATIENT_INSURANCE_INPUT_TEXT: str = "PIU_PATIENT_INSURANCE_INPUT_TEXT"

def generate_tag(key, sub_key, index=0):
    sub_key = sub_key.upper()
    if key == "patient_demographics":
        return "PIU_PATIENT_" + sub_key + "_INPUT_TEXT"
    elif key == "vital_signs" or key == "social_health_history":
        return "PIU_" + sub_key + "_INPUT_TEXT"
    elif key == "problems":
        return "PIU_PROBLEM_" + str(index) + "_" + sub_key + "_INPUT_TEXT"
    elif key == "sdoh_problems_health_concerns":
        return "PIU_SDOH_PROBLEM_" + str(index) + "_" + sub_key + "_INPUT_TEXT"
    elif key == "medications":
        return "PIU_MEDICATION_" + str(index) + "_NAME_INPUT_TEXT"
    elif key == "family_health_history":
        return "PIU_FAMILY_HEALTH_HISTORY_" + str(index) + "_INPUT_TEXT"
    elif key == "allergies_intolerances":
        return "PIU_ALLERGY_" + str(index) + "_" + sub_key + "_INPUT_TEXT"
    return ""
